[build]
  publish = "."
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/terms-of-use"
  to = "/terms-of-use.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 
